# Generated by Django 5.2.3 on 2025-07-02 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
