# Generated by Django 5.2.3 on 2025-07-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_userstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='Current_price',
            new_name='current_price',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='Description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='stocks',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
