# Generated by Django 5.2.3 on 2025-07-03 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_current_price_stocks_current_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='current_price',
            new_name='curr_price',
        ),
    ]
